config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  get 'computers/index'
  get '/results', to: 'computers#index'
  get '/test', to: 'computers#new'
  get 'computers/create'
  get 'computers/edit'
  get '/languages', to: 'page#languages'
  get '/systems', to: 'page#systems'
  get '/multi', to: 'page#multi'
  resources :computers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/computer.rb
class Computer < ApplicationRecord
  validates :userName, presence: true, length: { maximum: 60 }
  validates :category, presence: true, length: { maximum: 60 }
  validates :browser, presence: true, length: { maximum: 60 }
  validates :userAgentString, presence: true, length: { maximum: 255 }
  validates :time, presence: true
  validates_numericality_of :time
  validates :description, length: { maximum: 126 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  def index
    @computer = Computer.all
  end

  def show
    @computer = Computer.find(params[:id])
  end

  def new
    @computer = Computer.new
  end

  def create
    @computer = Computer.new(user_params)
    if @computer.save
      redirect_to computer_url(@computer)
    else
      render 'new'
    end
  end

  def edit
  end


    private

      def user_params
        params.require(:computer).permit(:userName, :category, :browser,
                     :userAgentString, :description, :time)
      end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def languages
  end

  def systems
  end

  def multi
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/computers/_errors.html.erb
<% if @computer.errors.any?  %>
  <div id = "error_explanation" >
    <div>
    The form contains <%= pluralize(@computer.errors.count, "error") %>
    </div>
    <ul>
    <% @computer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li> 
    <% end %>
    </ul>
  </div>
<% end %>

app/views/computers/create.html.erb
<h1>Computers#create</h1>
<p>Find me in app/views/computers/create.html.erb</p>

app/views/computers/edit.html.erb
<h1>Computers#edit</h1>
<p>Find me in app/views/computers/edit.html.erb</p>

app/views/computers/index.html.erb
<% provide(:title, 'Results' ) %>
<% @computer = @computer.sort { |a,b| a.time <=> b.time } %>

<h3>Systems Tested</h3>

<p> <%= (@computer.first).userName %> submitted the fastest system, a <%= (@computer.first).category %>, which needed <%=  (@computer.first).time %> ms. &nbsp; 
<%= link_to "show", :action => 'show', :id => @computer.first.id %>
<br>
<%= (@computer.last).userName %> submitted the slowest system, a <%= (@computer.last).category %>, which needed <%=  (@computer.last).time %> ms. &nbsp; 
<%= link_to "show", :action => 'show', :id => @computer.last.id %>
</p>

<h4>Desktops</h4>
<table>
  <tr>
    <td>Time in milliseconds </td> <td>&nbsp; | Browser |</td> 
    <td class="description" >Machine Description</td> <td>&nbsp;</td>
  </tr>
<% for computers in @computer %>
  <% if computers.category == "Desktop" %>
    <tr>
    <td>
      <div style="background-color: #69C; width:<%=
      (computers.time / 10)  %>px; max-width: 400px;">
      <%= computers.time %>
      </div>
    </td>
    <td>
      <%= computers.browser %>
    </td>
    <td class="description" >
      <%=  computers.description %>
    </td>
    <td>
      <%= link_to "show", :action => 'show', :id => computers %>
    </td>
    </tr>
  <% end %>
<% end %>
</table>

<h4>Mobile Devices</h4>
<table>
  <tr>
    <td>Time in milliseconds </td> <td>&nbsp; | Browser |</td>
<td class="description" >Machine Description</td>
  </tr>
<% for computers in @computer %>
  <% if (computers.category == "Mobile")  %>
    <tr>
    <td>
      <div style="background-color: #69C; width:<%=
      (computers.time / 10)  %>px; max-width: 400px;">
      <%= computers.time %>
      </div>
    </td>
    <td>
      <%= computers.browser %>
    </td>
    <td class="description" >
      <%=  computers.description %>
    </td>
    <td>
      <%= link_to "show", :action => 'show', :id => computers %>
    </td>
    </tr>
  <% end %>
<% end %>
</table>

<h4>Other</h4>
<table>
  <tr>
    <td>Time in milliseconds </td> <td>&nbsp; | Browser |</td>
<td class="description" >Machine Description</td>
  </tr>
<% for computers in @computer %>
  <% if computers.category == "Other" %>
    <tr>
    <td>
      <div style="background-color: #69C; width:<%=
      (computers.time / 10)  %>px; max-width: 400px;">
      <%= computers.time %>
      </div>
    </td>
    <td>
      <%= computers.browser %>
    </td>
    <td class="description" >
      <%=  computers.description %>
    </td>
    <td>
      <%= link_to "show", :action => 'show', :id => computers %>
    </td>
    </tr>
  <% end %>
<% end %>
</table>

app/views/computers/new.html.erb
<% provide(:title, 'Test' ) %>
<br><br>
<h2>Test complete!</h2>

<p id="testResult">
  Error: no result!
</p>



<br><br>

<%= form_for(@computer) do |f| %>
  <%= render 'computers/errors' %>

  <p>
    <%= f.label :userName, "Your name (required)" %><br>
    <%= f.text_field :userName %>
  </p>
  <p>
    <%= f.label :description, "Machine description (126 characters max)"%><br>
    <%= f.text_area :description %>
  </p>
  
  <%= f.hidden_field :category %>
  <%= f.hidden_field :browser %>
  <%= f.hidden_field :time %>
  <%= f.hidden_field :userAgentString %>                          

  <p>
    <%= f.submit "Submit" %>
  </p>

<% end %>

<%= javascript_pack_tag 'speedtest' %>
<%= javascript_pack_tag 'deviceDetect' %>

app/views/computers/show.html.erb
<h2>Your time has been recorded</h2>

<ul>
    <li>User: &nbsp; <%= @computer.userName %></li>
    <li>Browser: &nbsp; <%= @computer.browser %></li>
    <li>Machine type: &nbsp; <%= @computer.category %></li>
    <li>Computer description: &nbsp; <%= @computer.description%></li>
    <li>User agent: &nbsp; <%= @computer.userAgentString%></li>
    <li>Time to find primes under 20000: &nbsp; <%= @computer.time%>&nbsp; milliseconds.</li>
</ul>
<br>
<h2>Go to Results to see how your system compares</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Speedtest2 | <%= yield(:title) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all',
                      'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <div class="container">

      <div class="header">
        <h1>Test the speed of your computer!</h1>
      </div>

      <div class = "nav">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Test Speed", test_path %></li>
          <li><%= link_to "Results", results_path %></li>
          <li><%= link_to "Languages Compared", languages_path %></li>
          <li> <%= link_to "Systems Compared", systems_path %></li>
          <li> <%= link_to "Multithreaded Test", multi_path %></li>
       </ul>
      </div>

      <div class = "main">
        <%= yield %>
      </div>

      <div class ="footer">
      </div>
      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/page/browsers.html.erb
<% provide(:title, 'Systems Compared' ) %>
<h2>Smartphones are quick!</h2>

<p>Modern smartphones are surprisingly fast computing devices, despite their small size. A 2021 phone is likely faster than a laptop or desktop PC bought a few years ago. The speed of a moderately priced Apple phone has improved by nearly five fold since 2012. Smart phones appear to be leading the way in using smaller feature sizes on their chips, with PC processors lagging behind. The chart below shows the speed of a variety of phones and tablets, plus a laptop and a desktop. The phones win easily!</p>
<br>
<%= image_tag("systemTime2021.PNG", alt: "Bar chart of runtimes") %>
<br><br><br>
<h2>Which browser has the fastest Javascript engine?</h2>

<p>On the PC,  Edge is a little faster than Chrome, with Firefox taking a little longer. </p>
<br>
<%= image_tag("javascriptTimePC.png", alt: "Bar chart") %>
<br>
<p>On the Mac Firefox is the fastest, with Chrome just behind. Last year Safari performed well, but at the minute is surprisingly bad, running at about half the speed of the other two. </p>
<br>
<%= image_tag("javascriptTimeMac.png", alt: "Bar chart") %>
<br>

app/views/page/index.html.erb
<% provide(:title, 'Home' ) %>
<br><br>
<h2>How it works</h2>
<p>This site tests the speed of of your system by running a small program written in Javascript. It will work on anything from a modern desktop to an IPod. Javascript is a common web programming language which is used on most websites. This code runs automatically when you access the "Test Speed" page. It should complete in less than 5 seconds. 
</p>
<p>The code measures the time it takes the system to find every prime number less than 2,000,000. It provides an indication of the computer's speed at tasks which involve lots of arithmetic.</p>

<p>The time taken depends on both the speed of the computer and the speed of the Javascript engine in the browser being used. As of 2020 Safari seems to be the fastest, followed by Firefox and then Chrome. Microsoft Edge is the slowest, being only about half the speed of Firefox on my system. Find  browser comparisons under the "Browsers Compared" tab.</p>

<p>Please take the time to fill out the machine description on the "Test Speed" page. This will enter your computer into the database. The "Results" tab allows you to see other people's results. I hope over time to build up a picture of how different phones, tablets, laptops and desktops compare.</p>

<h2>Is your computer faster than mine?</h2>

<p>I have a desktop I built 2 years ago, a 4 year old laptop and an IPod Touch. The desktop is three times as fast as the laptop, and is 63 times faster than my IPod Touch. My desktop takes about 60 milliseconds to complete the task. The desktop doesn't have a very high end processor and I'm sure many out there can beat it. </p>

<h2>Which computer language is best?</h2>
<p>I started this project because I was interested in the speed differences between different languages. I first wrote the program in Java, and then ported the algorithm to Javascript and Ruby. Click the "Languages Compared" tab to see the source code in 3 different languages, and read my opinions on the strengths and weaknesses of each one.</p>

app/views/page/languages.html.erb
<% provide(:title, 'Languages Compared' ) %>
<h2>One algorithm. Three different languages.</h2>
<br>
<p>I implemented the same algorithm in 3 different languages, to check the runtime and expressiveness of each language. </p>
<br>
<%= image_tag("languageSpeedTest2020.png", alt: "Bar chart") %>
<br><br><br>
<h2>Java</h2>
<p>Java runs the fastest, finding every prime under 4,000,000 in 686 milliseconds on my system. I wrote the original code in Java, because it is the language with which I am most familiar. Java is also the least expressive language, with the most lines of code. </p>

<p>Java's massive library could greatly reduce coding time on projects which make use of it. The complex object oriented structure is of little help for my program, but could be very useful on large projects.</p>

<p>When it comes to deployability, Java has a big advantage over Ruby. Java claims to be 'write once, run anywhere', and Java virtual machines are available for most systems</p>

<h2>Javascript</h2>
<p>I was very surprised to find out the Javascript can run nearly as fast as Java. I had expected it to be much slower. On Chrome, it found every prime under 4,000,000 in 765 milliseconds.  On speed, Javascript now looks like a real rival to Java. </p>

<p>Javascript is also a more expressive language, getting the job done in fewer lines of code. I found it easy to port the code from Java to Javascript. However, it lacks Java's huge library and object oriented features. Javascript, of course, is unsuitable for any program that needs access to the hard drive.</p>

<p>The big advantage of Javascript is its incredible deployability. Simply put the code in a web page, and anybody anywhere can download and run the program when they access your web page. There is nothing to install, and no security worries.</p>


<h2>Ruby</h2>
<p>Ruby is the most expressive language, and fastest to write code in, but unfortunately it is very slow running. Finding every prime under 4000000 takes nearly 30 seconds on my system. This makes Ruby over 40 times slower than Java. I found Ruby 3.0.0 to be no faster than earlier versions.<p>
<br><br>
<h2>Code Listings</h2>
<div class="codeContainer1">
<div class="code">
<h2>Java (134 lines, 4066 characters)</h2>
<br>
<pre>
<code>
//This tests the speed of a computer by finding all the prime numbers under a 
//certain value. It is designed to use multiple threads
//It tests every odd integer (evenes are not prime) up to a maximum value
//For each candidate it finds the square root and then tests every odd number
//less than the square root

import java.util.*;
public class multithreadedComputerSpeedTest3_1 {
 
  //Set prime count to 4 because 2,3,5 and 7 are prime.
  //Start prime finding algorithm at 9
  private int primeCount = 4;
  public static final int START = 9;
  public static final int MAX = 4000000;
  //The next two values, thread count and problem sections, have to be set together.
  //They specify the number of threads and how the work is divided
  public static final int threadCount = 1;
  //Make array to specify which range of values each thread is reponsible for
  public static final int[] problemSections = {START, MAX};
  //Create flags which are set to true when the threads reach the end of their loops
  // Boolean instance variables are initialized automatically to false
  ArrayList&lt;Boolean> threadDone = new ArrayList&lt;Boolean>();
  //Instance variable to record start time
  Date startTime;
  

  public static void main(String[] args) {
    multithreadedComputerSpeedTest3_1 instance = new multithreadedComputerSpeedTest3_1();
    instance.go();
  }

  void go() {
    //Record start time
    startTime = new Date(); 

    //Make runnables
    Runnable[] runnables = new Runnable[threadCount];
    //Make runnables in loop
    for (int i=0; i&lt;threadCount; i++) {
      runnables[i] = new primeFinder(problemSections[i], problemSections[i+1]);
    }

    //Make threads
    Thread[] threads = new Thread[threadCount];
    //Create threads in loop
    for (int i = 0; i&lt;threadCount; i++) {
      threads[i] = new Thread(runnables[i]);
     }

     //Make loop to start threads
    for (int i=0; i&lt;threadCount; i++) {
      threads[i].start();
    }

    //As each thread completes, it adds an entry to the threadDone list.
    //When the length of the list equals the threadCount all threads have finished
    //At this point break loop, otherwise go back to sleep
    while (threadDone.size() &lt; threadCount) {
      try {
        Thread.sleep(2);
      } catch(Exception ex) {
        ex.printStackTrace();
      };
    }

    //Record finish time
    Date d10 = new Date();
    double runtime = (d10.getTime()-startTime.getTime())/1000.0;  //Get runtime in seconds
    System.out.println(primeCount + " primes found in " + runtime + " seconds.");

  }

  synchronized void incrementPrimeCount() {
    primeCount += 1;
  }


//Using an inner class
class primeFinder implements Runnable {
  int max = 0;
  int min = 0;

  primeFinder (int minParam, int maxParam) {
    min = minParam;
    max = maxParam;
  }

  public void run() {
    //Range is set by instance variables
    //In loop, test each number in a given range to see if it is prime
    //Don't need to test evens so ensure minimum value is odd
    //then increment by 2
    if(min%2 == 0) {
      min+=1;
    }
    for (int i = min; i&lt;=max; i+=2) {
      int candidate = i;

      //Find square root for each number in range
      int sqrt = (int) Math.sqrt(i);
      boolean isPrime = true;
      //Test for prime by dividing candidate by every odd integer 
      //less than the square root

        for (int j=3; j&lt;=sqrt; j+=2) {
          
          //Move to next if candidate is divisible
          if (candidate%j == 0){
            isPrime = false;
            break;
          }

        }

        if (isPrime == true) {
          incrementPrimeCount();
        }
    }

    //When loop completes print message in terminal
    //Record finish time
      Date now = new Date();
      //Get runtime in seconds
      double runtime = (now.getTime() - startTime.getTime())/1000.0;
      String threadName = Thread.currentThread().getName();
      System.out.println(threadName + " done at " + runtime);

      //Set flag to signal thread has completed
      threadDone.add(true);
  } 

}

}
</code>
</pre>
</div>

<div class="code">
<h2>Javascript (66 lines, 1864 characters)</h2>
<br>
<pre>
<code>
  //This tests the speed of a computer by finding all the prime numbers under a 
  //certain value. 
  //It tests every odd integer (evens are not prime) up to a maximum value
  //For each candidate it finds the square root and then tests every odd number
  //less than the square root


  //Set prime count to 4 because 2,3,5 and 7 are prime.
  //Start prime finding algorithm at 9
  let primeCount1 = 4;
  const START = 9;
  const MAX = 4000000;

  let startDate = new Date();
  let startTime = startDate.getTime();


  //Receive message from function and extract results
  let results = primeCounter(START, MAX, startTime);
  primeCount1 += results[0];


  //Record finish time
  let finishTime = new Date().getTime();
  let runtime = (finishTime - startTime);  

  let resultMessage = "Counting all primes under " + MAX; 
  resultMessage += " found " + primeCount1 + " primes in " + runtime + " milliseconds.";
  console.log(resultMessage);


  function primeCounter(min, max, startTime) {
    //Range is set by parameters
    //In loop, test each number in a given range to see if it is prime
    //Don't need to test evens so ensure minimum value is odd
    //then increment by 2
    if (min%2 == 0) {
      min+=1;
    }
    let primeCount2 = 0;
    for (let i = min; i<=max; i+=2) {
      let candidate = i;

      //Find square root for each number in range
      let sqrt = Math.sqrt(i);
      let isPrime = true;
      //Test for prime by dividing candidate by every odd integer 
      //less than the square root

      for (let j=3; j<=sqrt; j+=2) {

        //Move to next if candidate divisible
        if (candidate%j === 0) {
          isPrime = false;
          break;
        }
      }
      if (isPrime == true) {
        primeCount2++;
      }
    }
    //Make and return results array with number of primes and runtime
    let threadRunTime = new Date().getTime() - startTime;
    let results = [primeCount2, threadRunTime];
    return results;
  }

</code>
</pre>
</div>
</div>


<div class="codeContainer1">
<div class="code">
<h2>Ruby (56 lines, 1433 characters)</h2>
<pre>
<code>
#This tests the speed of a computer by finding all the prime numbers under a 
#certain value. 
#It tests every odd integer (evens are not prime) up to a maximum value
#For each candidate it finds the square root and then tests every odd number
#less than the square root

def primeCounter(min, max)
  #Range is set by parameters
  #In loop, test each number in a given range to see if it is prime
  
  primeCount2 = 0;
  for i in min..max do

    #Don't need to test evens so skip them
    next if (i%2 == 0) 

    #Find square root for each number in range
    candidate = i;
    sqrt = Math.sqrt(i).to_i;
    isPrime = true;
   
    #Test for prime by dividing candidate by every odd integer 
    #less than the square root
    for j in 2..sqrt do
      #Skip evens
      next if (j%2 == 0)
 
      #Move on if candidate is divisible by j
      if (candidate%j == 0) then
        isPrime = false;
        break;
      end
    end

    if (isPrime == true) then
        primeCount2 += 1;
    end
    
  end
  return primeCount2;
end

#Set prime count to 4 because 2,3,5 and 7 are prime.
#Start prime finding algorithm at 9
primeCount1 = 4;

Start = 9;
Max = 4000000;

startTime = Time.now
puts startTime;

primeCount1 += primeCounter(Start, Max);

finishTime = Time.now;
runTime = finishTime - startTime;
resultMessage = "Counting all primes under #{Max}, found #{primeCount1} primes";
resultMessage += " in #{runTime} seconds.";
puts resultMessage;
</code>
</pre>
<br><br><br>
</div>
</div>

app/views/page/multi.html.erb
<% provide(:title, 'Multithreaded Test' ) %>
<h2>Multi-threaded speed test</h2>
<p id="testResult">
  Error: no result!
</p>    

<%= javascript_pack_tag 'multithreadedSpeedtest' %>

app/views/page/systems.html.erb
<% provide(:title, 'Systems Compared' ) %>
<h2>Smartphones are quick!</h2>

<p>Modern smartphones are surprisingly fast computing devices, despite their small size. A 2021 phone is likely faster than a laptop or desktop PC bought a few years ago. The speed of a moderately priced Apple phone has improved by nearly five fold since 2012. Smart phones appear to be leading the way in using smaller feature sizes on their chips, with PC processors lagging behind. The chart below shows the speed of a variety of phones and tablets, plus a laptop and a desktop. The phones win easily!</p>
<br>
<%= image_tag("systemTime2021.PNG", alt: "Bar chart of runtimes") %>
<br><br><br>
<h2>Which browser has the fastest Javascript engine?</h2>

<p>On the PC,  Edge is a little faster than Chrome, with Firefox taking a little longer. </p>
<br>
<%= image_tag("javascriptTimePC.png", alt: "Bar chart") %>
<br>
<p>On the Mac Firefox is the fastest, with Chrome just behind. Last year Safari performed well, but at the minute is surprisingly bad, running at about half the speed of the other two. </p>
<br>
<%= image_tag("javascriptTimeMac.png", alt: "Bar chart") %>
<br>